server:
  port: 8001

spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/security
    dbcp2:
      #最小
      min-idle: 5
      #初始化
      initial-size: 5
      #最大
      max-idle: 20
      #配置获取连接等待超时的时间
      max-wait-millis: 60000
      #连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis:
  typeAliasesPackage: com.rz.security.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org:
      springframework:
        security: INFO
    com:
      rz:
        security:
          mapper: debug

